type FieldStat = { key: string; label: string; unit?: string; count: number; average: number | null };
type ActivityStat = { activity_id: string; count: number; average_hours: number | null; median_hours: number | null; interval_warning: boolean; fields: FieldStat[] };
type Activity = { id: string; name: string; color: string };
type Props = { child: { id: string; name: string }; dashboard: { activities: Activity[]; analytics: ActivityStat[]; gaps: unknown[] }; onBack: () => void };
const pretty = (value: number | null, suffix = "") => value === null ? "—" : `${value.toFixed(value < 10 ? 1 : 0)}${suffix}`;

export function AnalyticsView({ child, dashboard, onBack }: Props) {
  const activityById = new Map(dashboard.activities.map((activity) => [activity.id, activity]));
  return <main className="analytics-page"><header><button className="text-button" onClick={onBack}>← Timeline</button><button className="text-button report-button" onClick={() => window.open(`/api/children/${child.id}/export.report`, "_blank")}>Print / Save as PDF</button><p className="eyebrow">ACTIVITY DASHBOARD</p><h1>{child.name}’s care patterns</h1><p>Declared care gaps are excluded from all timing statistics.</p></header><section className="analytics-cards">{dashboard.analytics.map((stat) => { const activity = activityById.get(stat.activity_id); return <article key={stat.activity_id} className="analytics-card"><span className="analytics-dot" style={{ background: activity?.color }} /><h2>{activity?.name ?? "Activity"}</h2><div className="metric-grid"><div><p>Records</p><strong>{stat.count}</strong></div><div><p>Median interval</p><strong>{pretty(stat.median_hours, "h")}</strong></div><div><p>Average interval</p><strong>{pretty(stat.average_hours, "h")}</strong></div></div>{stat.interval_warning && <p className="analytics-warning">Average timing differs materially from the median. Review the pattern before relying on the average.</p>}{stat.fields.map((field) => <p className="field-stat" key={field.key}>{field.label}: <strong>{pretty(field.average)}{field.unit ? ` ${field.unit}` : ""}</strong> from {field.count} records</p>)}</article>; })}</section><footer>{dashboard.gaps.length} declared care gap{dashboard.gaps.length === 1 ? "" : "s"} excluded from analysis.</footer></main>;
}
