import { FormEvent } from "react";
import { Check, Pencil, Trash2 } from "lucide-react";

type Reminder = { id: string; kind: "interval" | "one_time"; interval_minutes?: number; scheduled_for?: string; title: string; activity_id?: string };
type Activity = { id: string; name: string };
type Props = { reminders: Reminder[]; activities: Activity[]; owner: boolean; onClose: () => void; onCreate: (event: FormEvent<HTMLFormElement>) => void; onEdit: (reminder: Reminder) => void; onComplete: (reminder: Reminder) => void; onDelete: (reminder: Reminder) => void };

export function RemindersPage({ reminders, activities, owner, onClose, onCreate, onEdit, onComplete, onDelete }: Props) {
  return <main className="detail-page"><header><button className="text-button" onClick={onClose}>← Timeline</button><p className="eyebrow">PASSIVE IN-APP REMINDERS</p><h1>Upcoming care</h1><p>Recurring reminders reset from the most recent matching activity.</p></header>{owner && <form className="detail-form" onSubmit={onCreate}><label>Title<input name="title" required placeholder="e.g. Vitamin D" /></label><label>Activity<select name="activityId"><option value="">None</option>{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.name}</option>)}</select></label><label>Schedule<select name="kind"><option value="interval">Repeat after last activity</option><option value="one_time">One time</option></select></label><label>Interval hours<input name="hours" type="number" min="1" defaultValue="3" /></label><label>One-time date/time<input name="when" type="datetime-local" /></label><button className="primary">Save reminder</button></form>}<section className="detail-list">{reminders.map((reminder) => <article key={reminder.id}><strong>{reminder.title}</strong><p>{reminder.kind === "interval" ? `Every ${Math.round((reminder.interval_minutes ?? 0) / 60)} hours after activity` : new Date(reminder.scheduled_for ?? "").toLocaleString()}</p><div className="inline-actions"><button onClick={() => onComplete(reminder)}><Check size={14} />Complete</button>{owner && <><button onClick={() => onEdit(reminder)}><Pencil size={14} />Edit</button><button className="danger" onClick={() => onDelete(reminder)}><Trash2 size={14} />Delete</button></>}</div></article>)}</section></main>;
}
